-- ===========================================================================
-- M1-C3 — FECHA A CORRIDA TOCTOU DO REGISTRO DE DOCUMENTO
-- ===========================================================================
-- DEFEITO CORRIGIDO
-- register_partner_application_document lia e validava o objeto em
-- storage.objects e só depois inseria o metadado. Entre a leitura e o
-- INSERT, o próprio solicitante podia APAGAR o objeto pela policy de DELETE,
-- porque ela só exigia que ainda não existisse metadado registrado — e nesse
-- instante, de fato, não existia.
--
-- Estados finais ruins que isso permitia:
--   A) metadado existe, objeto no Storage não existe mais;
--   B) metadado descreve o objeto validado, mas o caminho passou a apontar
--      para outro conteúdo (apagar e reenviar bytes diferentes no mesmo path).
--
-- Ambos violam a propriedade central do B5: o objeto verificado pelo backend
-- tem de ser o objeto permanentemente vinculado ao metadado.
--
-- DECISÃO DE PROJETO
-- O solicitante deixa de ter DELETE direto sobre objetos do bucket privado.
-- DELETE direto é uma superfície de mutação concorrente contra a RPC de
-- registro; sem ela, a corrida some por construção, e não por sincronização.
--
-- CONSEQUÊNCIA ACEITA NO M1
-- Uma falha de registro após o upload pode deixar um objeto órfão. O órfão
-- não tem metadado, não aparece na UI, não é revisável e não é reutilizável
-- (o path novo é sempre único). A limpeza controlada fica para um fluxo
-- server-side posterior; NÃO é construída agora.
--
-- Nada mais é ampliado: bucket segue privado, upload segue restrito à pasta
-- da própria aplicação, leitura segue pelas regras existentes, isolamento
-- entre aplicações, acesso do admin e imutabilidade de path registrado
-- permanecem como estão.
-- ===========================================================================

DROP POLICY m1_partner_docs_titular_delete ON storage.objects;

-- Nenhuma policy de DELETE é criada em seu lugar. Com RLS ativa em
-- storage.objects e sem policy para o comando, DELETE é negado para toda
-- role do Data API — inclusive para o dono do próprio objeto.
--
-- service_role e o owner do schema seguem com as capacidades que já tinham
-- por privilégio de base; nenhum GRANT novo é concedido aqui.
--
-- NOTA — POR QUE NÃO HÁ COMMENT ON TABLE AQUI
-- Uma versão anterior desta migration executava
--   COMMENT ON TABLE storage.objects IS '...'
-- para registrar a decisão. Isso é inválido no stack Supabase real:
-- COMMENT ON TABLE exige ser dono da tabela, e storage.objects pertence a
-- supabase_storage_admin, não a postgres. A instrução falharia com
-- "must be owner of table objects" e abortaria o db reset.
--
-- O harness auxiliar não reproduziu o defeito porque ali storage.objects é
-- criada por postgres, que passa a ser dona. É mais um ponto em que o
-- ambiente auxiliar diverge do remoto.
--
-- Além disso, storage.objects é objeto gerenciado pelo Supabase: alterar seu
-- comentário é mutação de metadado que não nos pertence. A decisão fica
-- registrada aqui, no arquivo da própria migration, que é onde ela tem valor
-- de auditoria.
